// SPEC-DERIVED-PHASE2G  HALT #18 (14 tests)
using System; using System.Threading.Tasks; using Microsoft.VisualStudio.TestTools.UnitTesting; using Moq; using TaskTree.Core.Abstractions; using TaskTree.Core.Enums; using TaskTree.Core.Models; using TaskTree.Modules.Snooze; using TaskTree.TestSupport;
namespace TaskTree.Modules.Snooze.Tests{[TestClass]public class SnoozeServiceTests{static readonly DateTimeOffset T=new(2026,6,1,12,0,0,TimeSpan.Zero);static(SnoozeService svc,FakeClock clock,Mock<IComplianceCore> comp)Build(){var comp=new Mock<IComplianceCore>(MockBehavior.Strict);comp.Setup(c=>c.AuditAsync(It.IsAny<AuditEntry>())).Returns(Task.CompletedTask);var log=new Mock<IAppLogger>(MockBehavior.Loose);var clock=new FakeClock(T);return(new SnoozeService(new InMemorySecureStore(),comp.Object,clock,log.Object),clock,comp);} [TestMethod]public void Constructor_NullArgs_Throw(){var s=new InMemorySecureStore();var c=new Mock<IComplianceCore>().Object;var clk=new FakeClock();var l=new Mock<IAppLogger>().Object;Assert.ThrowsException<ArgumentNullException>(()=>new SnoozeService(null!,c,clk,l));Assert.ThrowsException<ArgumentNullException>(()=>new SnoozeService(s,null!,clk,l));Assert.ThrowsException<ArgumentNullException>(()=>new SnoozeService(s,c,null!,l));Assert.ThrowsException<ArgumentNullException>(()=>new SnoozeService(s,c,clk,null!));}
[TestMethod]public async Task GetAsync_NoSnooze_ReturnsNull(){var(s,_,_)=Build();Assert.IsNull(await s.GetAsync(Guid.NewGuid()));}
[TestMethod]public async Task SnoozeAsync_Valid_Persists(){var(s,_,_)=Build();var id=Guid.NewGuid();await s.SnoozeAsync(id,T.AddMinutes(10),SnoozeReason.UserRequested);Assert.IsNotNull(await s.GetAsync(id));}
[TestMethod]public async Task GetAsync_AfterSnooze_ReturnsState(){var(s,_,_)=Build();var id=Guid.NewGuid();await s.SnoozeAsync(id,T.AddMinutes(10),SnoozeReason.QuietHours);Assert.AreEqual(SnoozeReason.QuietHours,(await s.GetAsync(id))!.Reason);}
[TestMethod]public async Task SnoozeAsync_EmptyTaskId_Throws(){var(s,_,_)=Build();await Assert.ThrowsExceptionAsync<ArgumentException>(()=>s.SnoozeAsync(Guid.Empty,T.AddMinutes(1),SnoozeReason.UserRequested));}
[TestMethod]public async Task SnoozeAsync_PastUntil_Throws(){var(s,_,_)=Build();await Assert.ThrowsExceptionAsync<ArgumentOutOfRangeException>(()=>s.SnoozeAsync(Guid.NewGuid(),T,SnoozeReason.UserRequested));}
[TestMethod]public async Task SnoozeAsync_InvalidReason_Throws(){var(s,_,_)=Build();await Assert.ThrowsExceptionAsync<ArgumentException>(()=>s.SnoozeAsync(Guid.NewGuid(),T.AddMinutes(1),(SnoozeReason)99));}
[TestMethod]public async Task SnoozeAsync_AuditsCreated(){var(s,_,c)=Build();await s.SnoozeAsync(Guid.NewGuid(),T.AddMinutes(1),SnoozeReason.UserRequested);c.Verify(x=>x.AuditAsync(It.Is<AuditEntry>(e=>e.Action=="SnoozeCreated")),Times.Once);}
[TestMethod]public async Task SnoozeAsync_RaisesChangedCreated(){var(s,_,_)=Build();var raised=false;s.SnoozeChanged+=(o,e)=>raised=e.Kind==SnoozeChangeKind.Created;await s.SnoozeAsync(Guid.NewGuid(),T.AddMinutes(1),SnoozeReason.UserRequested);Assert.IsTrue(raised);}
[TestMethod]public async Task ClearAsync_NoExisting_IsNoOp(){var(s,_,c)=Build();await s.ClearAsync(Guid.NewGuid());c.Verify(x=>x.AuditAsync(It.Is<AuditEntry>(e=>e.Action=="SnoozeCleared")),Times.Never);}
[TestMethod]public async Task ClearAsync_Existing_Removes(){var(s,_,_)=Build();var id=Guid.NewGuid();await s.SnoozeAsync(id,T.AddMinutes(1),SnoozeReason.UserRequested);await s.ClearAsync(id);Assert.IsNull(await s.GetAsync(id));}
[TestMethod]public async Task ClearAsync_AuditsCleared(){var(s,_,c)=Build();var id=Guid.NewGuid();await s.SnoozeAsync(id,T.AddMinutes(1),SnoozeReason.UserRequested);await s.ClearAsync(id);c.Verify(x=>x.AuditAsync(It.Is<AuditEntry>(e=>e.Action=="SnoozeCleared")),Times.Once);}
[TestMethod]public async Task GetAsync_Expired_AutoClears(){var(s,clk,_)=Build();var id=Guid.NewGuid();await s.SnoozeAsync(id,T.AddMinutes(1),SnoozeReason.UserRequested);clk.Advance(TimeSpan.FromMinutes(2));Assert.IsNull(await s.GetAsync(id));}
[TestMethod]public async Task GetAllAsync_ReturnsActiveSnoozes(){var(s,_,_)=Build();await s.SnoozeAsync(Guid.NewGuid(),T.AddMinutes(1),SnoozeReason.UserRequested);Assert.AreEqual(1,(await s.GetAllAsync()).Count);}}}
